# Generated by Django 3.1.2 on 2020-10-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
    ]
