# Generated by Django 3.1.2 on 2020-10-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20201012_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
