# Generated by Django 3.1.2 on 2020-10-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='img/materlize.png', upload_to='img/'),
        ),
    ]
