# Generated by Django 3.1.2 on 2020-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20201025_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
